# Config format schema number
format_version: 4


debug: True

data_path: "/Users/fenglan/Downloads/waymo/v2_data"

max_epoch: 50
num_workers: 0
batch_size: 16
lr: 0.0003
weight_decay: 0.0004
device: 'cpu'
phase: 'training'
data_usage: 1
model: "act"
recache: True
pred_len: 90

# eval config
need_eval: True
eval_data_start_index: 0
eval_data_usage: 0
eval_batch_size: 1
eval_frequency: 1


