# Config format schema number
format_version: 4
map_size: 60
device: 'gpu'

debug: False
data_path: '/data0/pengzh/'
sample_gap: 20
use_cache: True

dataset: ['waymo', 'nuplan', 'pg']
data_usage: [4,4,4]
single_frame: False
data_perc: 0.3

max_epoch: 100
num_workers: 10
batch_size: 64
lr: 0.0003
weight_decay: 0.0004
hidden_dim: 1024
gaussian_comp: 5

pad_num: 0
min_agent: 8
draw: True

strategy: ddp


